pages:
  stage: deploy
  script:
  - mkdir -p public/eclipse
  - tar xvzf build/emt-plugin-latest.tar.gz -C public/eclipse
  - cp build/web-extension-latest.xpi public
  - cp build/index.html public
  artifacts:
    paths:
    - public
  only:
  - master
