/*
 * generated by Xtext
 */
package edu.udea.vulnfinder.gram.ui.contentassist

import edu.udea.vulnfinder.gram.ui.contentassist.AbstractSecLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class SecLanguageProposalProvider extends AbstractSecLanguageProposalProvider {
}
