/*
 * generated by Xtext
 */
package edu.udea.vulnfinder.gram.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SecLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/udea/vulnfinder/gram/parser/antlr/internal/InternalSecLanguage.tokens");
	}
}
