/*
 * generated by Xtext
 */
package edu.udea.vulnfinder.gram.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SecLanguageUiModule extends edu.udea.vulnfinder.gram.ui.AbstractSecLanguageUiModule {
	public SecLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
