/*
 * generated by Xtext
 */
package edu.udea.vulnfinder.gram;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SecLanguageRuntimeModule extends edu.udea.vulnfinder.gram.AbstractSecLanguageRuntimeModule {
	
}
